name = "inky-clip"
main = "worker.js"
compatibility_date = "2023-05-18"

[vars]
YOUTUBE_API_KEY = "your_youtube_api_key_here"
GEMINI_API_KEY = "your_gemini_api_key_here"

[[routes]]
pattern = "/*"
script = "worker.js"

[site]
bucket = "./public"
